server:
  port: 8080
spring:
  application:
    name: "NequiChallenge"
  devtools:
    add-properties: false
  profiles:
    include: null
adapters:
  r2dbc:
    host: ${DB_HOST}
    port: ${DB_PORT}
    database: ${DB_NAME}
    schema: "public"
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    sslMode: ${DB_SSL_MODE:disable}
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
springdoc:
  api-docs:
    path: "/v1/api-docs"
    version: "openapi_3_0"
  swagger-ui:
    url: "/v1/api-docs"
    enable: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
